// Blur image placeholder generated on: https://png-pixel.com/

export enum IMAGES {
  BLUR_PLACEHOLDER_PRIMARY = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8f1xnEwAHZQKm70UdTgAAAABJRU5ErkJggg==',
  BLUR_PLACEHOLDER_GREEN = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mMUme64CQADUwGghIPTogAAAABJRU5ErkJggg==',
}
